# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-case-conflict
      - id: debug-statements
      - id: detect-private-key

  - repo: local
    hooks:
      - id: rustfmt
        name: rustfmt
        entry: cargo fmt -- --check
        language: system
        pass_filenames: false
        files: \.rs$

      - id: clippy
        name: clippy
        entry: cargo clippy -- -D warnings
        language: system
        pass_filenames: false
        files: \.rs$

  - repo: https://github.com/crate-ci/typos
    rev: v1.15.10
    hooks:
      - id: typos
        args: [--write-changes]

  - repo: local
    hooks:
      - id: cargo-deny
        name: cargo-deny
        entry: cargo deny check
        language: system
        pass_filenames: false
        always_run: true
        files: \.toml$

      - id: cargo-test
        name: cargo test
        entry: cargo test
        language: system
        pass_filenames: false
        always_run: true