[template]
# Template configuration for cargo-generate
# See: https://github.com/cargo-generate/cargo-generate

# Files and directories to exclude from template processing
exclude = [
    "cliff.toml",  # Contains git-cliff template syntax
    ".github/workflows/build.yml",  # Contains GitHub Actions template syntax
    "target/**",   # Build artifacts
    "Cargo.lock",  # Lock file
    ".git",        # Git directory
    "TEMPLATE_IMPROVEMENTS.md",  # Template documentation
    ".rust-version",  # Rust version file
    "rust-toolchain.toml",  # Rust toolchain configuration
]

# Template variables that will be prompted to the user
[template.variables]
project-name = { prompt = "Project Name", default = "my-rust-project" }
author = { prompt = "Author Name", default = "Your Name" }
email = { prompt = "Author Email", default = "your.email@example.com" }
description = { prompt = "Project Description", default = "A Rust project" }
license = { prompt = "License", default = "MIT" }
repository = { prompt = "Repository URL", default = "https://github.com/username/my-rust-project" }
